main/urls.py
from django.urls import path
from .views import MainIndex, CategoryView

app_name = 'main'
urlpatterns = [
    path('', MainIndex.as_view(), name="index"),
    path('g/<int:gid>/', CategoryView.as_view(), name="index"),
    # path('', ChannelView.as_view(), name="index"),
    # path('', ProgramView.as_view(), name="index"),
]

tvdastur/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
urlpatterns = [

]
urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.base import Model
from django.utils.translation import get_language


class Category(models.Model):
    category_uz = models.CharField(max_length=50)
    category_ru = models.CharField(max_length=50)

    def __str__(self):
        return self.category_uz

    @property
    def category(self):
        return getattr(self, 'category_{}'.format(get_language()))


class Channel(models.Model):
    Category = models.ManyToManyField(Category)
    Channel_name = models.CharField(max_length=100)
    Channel_image = models.ImageField()

    def __str__(self):
        return self.Channel_name


class Program(models.Model):
    Channel = models.ForeignKey(Channel, on_delete=models.RESTRICT)
    Program_name = models.CharField(max_length=200)
    Program_time = models.DateTimeField(auto_now_add=False)

    def __str__(self):
        return self.Program_name

main/views.py
from django.shortcuts import render
from django.views.generic import View
from .models import Category, Channel, Program
# from django.utils.translation import gettext_lazy as _


class MainIndex(View):
    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)

    def get(self, request, pid=None):
        p = request.GET.get('p', '')
        channel = Channel.objects.filter(Channel_name__icontains=p).order_by('-id').all()
        # if pid == id:
        #     program = Program.objects.filter(Channel=id).all
        # else:
        #     program = Program.objects.none()
        return render(request, 'main/index.html', {
            'category': Category.objects.all(),
            'channel': channel,
            'program': Program.objects.all()
        })


class CategoryView(View):
    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)

    def get(self, request, gid=None):
        p = request.GET.get('p', '')
        if gid is None:
            channel = Channel.objects.filter(Channel_name__icontains=p).all()
        else:
            channel = Channel.objects.filter(Category=gid, Channel_name__icontains=p).all()
        return render(request, 'main/index.html', {
            'category': Category.objects.all(),
            'channel': channel,
            'program': Program.objects.all()
        })

# class ChannelView(View):
#     def setup(self, request, *args, **kwargs):
#         super().setup(request, *args, **kwargs)
#
#     def get(self, request, pid=None):
#         if pid is None:
#             program = Program
#         else:
#             program = Program.objects.filter(Channel=pid).all()
#
#         return render(request, 'main/index.html', {
#             'category': Category.objects.all(),
#             'channel':
#         })


# class ProgramView(View):
#     def setup(self, request, *args, **kwargs):
#         super().setup(request, *args, *kwargs)
#
#     def det(self, request):
#         return render(request, 'main/index.html')

templates/layout.html
{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!doctype html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ request.title|default:"tvdastur" }}</title>
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'main:index' %}">TVDASTUR</a>
                <form method="get" action="{{ request.path }}" class="form-inline">
                    <input class="form-control mr-sm-2" type="text" name="p" value="{{ request.GET.p }}" placeholder="{% trans 'Kanal nomi kiriting' %}" aria-label="{% trans 'Kanal nomi kiriting' %}">
                    <button class="btn btn-outline-info my-2 my-sm-0" type="submit">{% trans "Qidirish" %}</button>
                </form>
                <a href="admin/" class="btn btn-outline-info">{% trans "Admin" %}</a>
                <li class="nav-item dropdown ml-3">
                    <a class="active lang-link" id="navbarDropdown" role="button" data-toggle="dropdown">
                        {% for language in LANGUAGES %}
                            {% if  language.0 == LANGUAGE_CODE %}
                                {{ language.1 }}
                            {% endif %}
                        {% endfor %}
                    </a>
                    <div class="dropdown-menu">
                        {% for language in LANGUAGES %}
                            <a class="dropdown-item" href="/{{ language.0 }}{{ request.get_full_path|slice:"3:" }}">{{ language.1 }}</a>
                        {% endfor %}
                    </div>
                </li>
            </div>
        </nav>
{#        {{ LANGUAGES }} // {{ LANGUAGE_CODE }}#}
            {% block content %}{% endblock %}
    </div>

    <script src="{% static 'vendor/jquery.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/main/index.html
{% extends 'layout.html' %}
{% load i18n %}
{% block content %}

    <div class="btn-group" style="margin-top: 5px">
      <button type="button" class="btn btn-outline-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {% trans 'Kategoriyalar' %}
      </button>
      <div class="dropdown-menu">
          {% for g in category %}
            <a href="{% url 'main:index' g.id %}" class="dropdown-item">{{ g.category }}</a>
          {% endfor %}
      </div>
    </div>

    <div>
        {% for chn in channel %}
           <div class="row">
            <a><img src="{{ chn.Channel_image.url }}" style="width: 100px; height: 50px" class="logo"> {{ chn.Channel_name }}</a>
           </div>
        {% endfor %}
    </div>
    <div>
        {% for prg in program %}
            {{ prg.Program_time }} - {{ prg.Program_name }}
        {% endfor %}
    </div>

{% endblock %}
{#{{ chn.Channel_name }} <img src="{{ chn.Channel_image.url }}"/>#}
{#<img src="..." alt="..." class="rounded-circle">#}
{#    <div class="btn-group-vertical" style="margin-top: 5px">#}
{#         {% for g in category %}#}
{#            <a href="{% url 'main:index' g.id %}" class="btn btn-outline-info m-sm-auto{% if g.id == request.resolver_match.kwargs.gid %}active{% endif %}">{{ g.name }}</a>#}
{#         {% endfor %}#}
{#    </div>#}